In [56]:
 import numpy as np
 import pandas as pd
 a = np.array([0, 1, 2, 3])# 下面讨论了 一维 Numpy array 的所有操作符 包括 +,-,*,/,=,+=,>,< 
                           # 四个重要函数(std(),mean(),max(),argmax()) 以及 array slice 包括 reverse array

In [22]:
a.dtype #input dtype to check data type

dtype('int64')

In [23]:
a[-1]  # index -1 means the last element(数据访问)

3

In [30]:
a[::2] # [start:end:step] Pay attention, if step is negative, it will become [end, start, step] (Array Slice)

array([0, 2])

In [54]:
a = np.array([0, 1, 2, 3])
a[::-1] # if step is negative, it will automaticly become [end, start, step] (Array Reverse)

array([3, 2, 1, 0])

In [34]:
a[0:3:-2] # reverse error

array([], dtype=int64)

In [55]:
a = np.array([0, 1, 2, 3])
a[::-2] # if step is negative, it will automaticly become [end, start, step] (Array Reverse)

array([3, 1])

In [37]:
b = a
a += [0,1,2,3]
print(a)
print(b) # += 是原位操作符，不产生新数组所以a与b同时被改变

[0 2 4 6]
[0 2 4 6]


In [38]:
a = np.array([0, 1, 2, 3])
b = a
a = a + [0,1,2,3]
print(a)
print(b) # = 是非原位操作符，a + [0,1,2,3]会产生新数组，所以a为新数组，但是b还是原来的旧数组没有发生改变

[0 2 4 6]
[0 1 2 3]


In [40]:
a = np.array([0, 1, 2, 3])
slice1 = a[:1]
slice1[0] = 100
print(a)  #需要注意的是，slice操作为了保证效率并不会产生新的的数组，所以在slice上做的所有操作都会反映到原数组上

[100   1   2   3]


In [44]:
 a = np.array([10, 70, 200, 3000])
 (a-a.mean())/a.std() # numpy 中的加减乘除(+,-,*,/)都是针对数组里的每一个元素的 a.mean(),a.std(),a.max(),a.argmax()是numpy的四个重要函数

array([-0.64260421, -0.5950039 , -0.49186989,  1.72947801])

In [50]:
 age = np.array([10, 20, 22, 30, 40])
 age > 20 # 当一个Numpy Array 使用 > 或 < 比较符时，返回的是判断结果的布尔数组

array([False, False,  True,  True,  True], dtype=bool)

In [51]:
 age = np.array([10, 20, 22, 30, 40])
 name = np.array(['Jack', 'Siwei','Micheal','Stephen','Gao'])
 name[ age > 20 ]# 当应用 > 或 < 比较符到下标中时，如果为TRUE会返回，如果为FALSE则不会返回

array(['Micheal', 'Stephen', 'Gao'], 
      dtype='|S7')

In [62]:
# Series 是pandas的一维数组，DataFrame的每一列都是一个 Series
c = pd.Series([1,2,3,4],index=['A','B','C','D']) #pd.Series() 与 np.array() 的最大区别是，pd中有index也就是行索引值
print(c)

A    1
B    2
C    3
D    4
dtype: int64


In [60]:
c = pd.Series([1,2,3,4])# 如果没有指定index则pandas会默认index从0开始，如需要列索引值则应该把 Array 换为 Dictionary
print(c)

0    1
1    2
2    3
3    4
dtype: int64


In [64]:
c = pd.Series([1,2,3,4],index=['A','B','C','D']) #两个Series相加是按照index相加的，如能匹配上index则相加
d = pd.Series([1,2,3,4],index=['C','D','E','F']) #如果不能匹配的上则为NaN
e = c+d
print(e)

A    NaN
B    NaN
C    4.0
D    6.0
E    NaN
F    NaN
dtype: float64


In [65]:
e.dropna() # dropna() 函数可以将value为NaN的项去掉

C    4.0
D    6.0
dtype: float64

In [70]:
f = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]]) #二维 Numpy Array
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [71]:
print(f[0,:]) # 取第0行数据

[0 1 2 3]


In [72]:
print(f[:,0]) # 取第0列数据

[0 4 8]


In [73]:
f.mean() # Numpy 中的 mean() 函数与pandas不同, 它对二维数组的每一个值都求平均，得到一个整体的平均数

5.5

In [75]:
f.mean(axis=0,dtype=int) #axis 是numpy中的数轴，会得到一个一维数组，数组中每一个元素都是每一列的平均数

array([4, 5, 6, 7])

In [76]:
f.mean(axis=1,dtype=int) # 数组中每一个元素都是每一行的平均数

array([1, 5, 9])

In [77]:
f[0,:].max() #Numpy中获取第一行最大值的函数（与pandas有很大不同）

3

In [78]:
f[0,:].argmax() #Numpy中获取第一行最大值下标的函数（与pandas有很大不同）

3

In [79]:
g = np.array([[0, 'S', 2, 3],[4, 'A', 6, 7],[8, 'B', 10, 11]]) # Numpy Array 不支持每一列数据类型不一样
print(g)

[['0' 'S' '2' '3']
 ['4' 'A' '6' '7']
 ['8' 'B' '10' '11']]


In [80]:
g[0,:].max() #当有一列数据类型不一样时，Numpy会报错

TypeError: cannot perform reduce with flexible type

In [81]:
# 大部分的CSV文件，每一列的数据类型都不一样，所以Numpy不适合，pandas的 DataFrame 明显更适合
# 字典算行索引值， index算列索引值，DataFrame两者都有
ridership_df = pd.DataFrame({
    'R003':[0,1478,1613,1516,95],
    'R004':[0,3877,4088,3392,0],
    'R005':[0,3674,3991,3826,1],
    'R006':[0,2328,6461,4979,3]
},index = [
    '05-01-11','05-02-11','05-03-11','05-04-11','05-05-11'
])

In [82]:
print(ridership_df) # 字典里的值为行索引值，index里面的值为列索引值

          R003  R004  R005  R006
05-01-11     0     0     0     0
05-02-11  1478  3877  3674  2328
05-03-11  1613  4088  3991  6461
05-04-11  1516  3392  3826  4979
05-05-11    95     0     1     3


In [83]:
ridership_df.head() # head函数查看头几行数据

R003  R004  R005  R006
05-01-11     0     0     0     0
05-02-11  1478  3877  3674  2328
05-03-11  1613  4088  3991  6461
05-04-11  1516  3392  3826  4979
05-05-11    95     0     1     3

In [84]:
ridership_df.describe() # describe 函数得到基本函数的数据

R003         R004         R005         R006
count     5.000000     5.000000     5.000000     5.000000
mean    940.400000  2271.400000  2298.400000  2754.200000
std     817.277982  2088.794341  2100.679723  2916.610481
min       0.000000     0.000000     0.000000     0.000000
25%      95.000000     0.000000     1.000000     3.000000
50%    1478.000000  3392.000000  3674.000000  2328.000000
75%    1516.000000  3877.000000  3826.000000  4979.000000
max    1613.000000  4088.000000  3991.000000  6461.000000

In [85]:
ridership_df.mean() # pd中的 mean 不会求整体平均值而是会求每一列的平均值

R003     940.4
R004    2271.4
R005    2298.4
R006    2754.2
dtype: float64

In [96]:
print(ridership_df.iloc[1]) # .iloc[1] 函数可以按照序号来获取行数据，对应 Numpy 是a[1,:]

R003    1478
R004    3877
R005    3674
R006    2328
Name: 05-02-11, dtype: int64


In [98]:
print(ridership_df.iloc[1,2]) # .loc[1,2] 获取第一行第二列的数据，对应 Numpy 是a[1,2]

3674


In [97]:
print(ridership_df.loc['05-02-11']) # .loc['05-02-11'] 函数可以按照index的值来获取行数据

R003    1478
R004    3877
R005    3674
R006    2328
Name: 05-02-11, dtype: int64


In [107]:
print(ridership_df['R003']) # 获取第0列的数据，对应 Numpy 是a[:,0]

05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1516
05-05-11      95
Name: R003, dtype: int64


In [108]:
print(ridership_df['R003'][1])# 获取第0列第1行的数据，对应 Numpy 是a[1,0]

1478


In [109]:
ridership_df['R003'].max() # 在当前列求最大值

1613

In [111]:
ridership_df.iloc[1].max() # 在当前行求最大值

3877

In [112]:
ridership_df.values.mean() # pd 在求整体平均值时一定要加上.value

2066.0999999999999

In [114]:
# panda 计算两个变量的相关性, Pearsons,r 为两个变量的相关系数 -1为负相关，0为无关，1为正相关
def correlation(x,y):
    std_x = (x-x.mean())/x.std(ddof=0)
    std_y = (y-y.mean())/y.std(ddof=0)
    return (std_x*std_y).mean()

In [147]:
# apply()函数，对一列元素应用自定义的转换函数
applymap = pd.DataFrame({
        'Grade':[70,90,30,50,80,100],
        'Name':['Jack','Micheal','Stephen','Gao','Helly','Siwei']}
)

In [127]:
applymap.head()

Grade     Name
0     70     Jack
1     90  Micheal
2     30  Stephen
3     50      Gao
4     80    Helly

In [128]:
applymap['Grade'] # 选取你想转换的那一列

0     70
1     90
2     30
3     50
4     80
5    100
Name: Grade, dtype: int64

In [134]:
# 写出针对单个数据的转换函数
def convert_grade(grade):
    if grade > 90:
       return 'A'
    elif grade > 70:
       return 'B'
    elif grade > 60:
       return 'C'
    else:
       return 'D'


In [149]:
# 使用 apply 函数将转换函数应用到那一列
applymap['Grade'] = applymap['Grade'].apply(convert_grade)
applymap.head()

Grade     Name
0     C     Jack
1     B  Micheal
2     D  Stephen
3     D      Gao
4     B    Helly

In [170]:
# 使用sort_values()函数为每一个Series排序
sort_column = pd.DataFrame({
        'Grade':[70,90,30,120,80,100]}
)
sort_column.head()

Grade
0     70
1     90
2     30
3    120
4     80

In [158]:
sort_column['Grade'].sort_values(ascending=False)

3    120
5    100
1     90
4     80
0     70
2     30
Name: Grade, dtype: int64

In [159]:
sort_column.head()

Grade
0     70
1     90
2     30
3    120
4     80

In [160]:
def sort_decending(column):
    sort_column = column.sort_values(ascending=False)
    return sort_column[1]

In [161]:
sort_decending(sort_column['Grade'])

90

In [162]:
sort_column.apply(sort_decending)

Grade    90
dtype: int64

In [163]:
sort_column.head()

Grade
0     70
1     90
2     30
3    120
4     80

In [175]:
test = sort_column['Grade'].sort_values(ascending=False)
print(test)

3    120
5    100
1     90
4     80
0     70
2     30
Name: Grade, dtype: int64


In [176]:
sort_column['Grade'] = test #sort之后的Series不能赋值给原DataFrame，因为index序号已经改变了，所以只能调查不能更改
sort_column.head()

Grade
0     70
1     90
2     30
3    120
4     80

In [ ]:
# DataFrame 与 Series 相加
# 默认情况是 DataFrame的每一列与 Series的每一个值对应相加

In [177]:
s = pd.Series([1,2,3,4])
df = pd.DataFrame({
        0:[10,20,30,40],
        1:[50,60,70,80],
        2:[90,100,110,120],
        3:[130,140,150,160]}
)
df.head()

0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

In [178]:
df+s # DataFrame的第一列与 Series的第一个值相加，DataFrame的第二列与 Series的第二个值相加

0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164

In [179]:
s = pd.Series([1,2,3,4])
df = pd.DataFrame({
        0:[10,20,30,40]}
)
df+s # 当DataFrame只有一列时，Series的后面几个数会导致结果有NaN

0   1   2   3
0  11 NaN NaN NaN
1  21 NaN NaN NaN
2  31 NaN NaN NaN
3  41 NaN NaN NaN

In [181]:
df.add(s,axis='columns')# df.add() 函数可以调整相加的数轴，’column‘会把Series加到列上

0   1   2   3
0  11 NaN NaN NaN
1  21 NaN NaN NaN
2  31 NaN NaN NaN
3  41 NaN NaN NaN

In [182]:
df.add(s,axis='index')# ’index‘会把Series加到行上

0
0  11
1  22
2  33
3  44